language: c

os: linux

dist: xenial

compiler:
  - gcc

before_install:
  sudo add-apt-repository ppa:snaipewastaken/ppa -y && sudo apt-get update && sudo apt-get install criterion-dev -y

script:
  - make
  - make tests_run