language: c

os: linux

dist: xenial

compiler:
  - gcc

before_install:
  sudo add-apt-repository ppa:snaipewastaken/ppa --force-yes && sudo apt-get update --force-yes && sudo apt-get install criterion-dev --force-yes

script:
  - make
  - make tests_run